### ISSUE TITLE
App available as user/account app, instead of server app?

### ISSUE THREAD

**Issue by sebastientromp** [iHeroGH/StalkerBot#29]
Hello!

I'm interesting in using StalkerBot as a user app, in order for it to ping me whenever a keyword is mentioned in any of the servers I'm in.
When adding the app, I do have the option to "add it everywhere", but after doing so I can't access any of its slash commands (and so can't configure it).

Is there something I need to do to be able to use it as a user app?

**Comment by iHeroGH** [comment]
Hello Sebastien,

To my understanding, adding a bot as a user app simply allows you to run commands in any server. Meaning, the bot wouldn't be able to *read* messages in servers that it is not in. 

If the bot is unable to receive message events from servers, it is unable to scan those messages for keywords.

**Comment by sebastientromp** [comment]
Oh I see. I thought the app would somehow be able to use my permissions to read all messages that I myself can read, and act on them.

> adding a bot as a user app simply allows you to run commands in any server

This doesn't seem to be working for me, as I don't have the `/add` (or any other slash command) available in any of the servers I'm in, even though I have added the bot to my apps.

**Comment by 4Kaylum** [comment]
StalkerBot is not currently configured as a user-installable app, for the reasons given above. 

The bot will *only* function when added to individual servers as a bot user. Unfortunately your suggestion is not feasible.

**Comment by sebastientromp** [comment]
Thanks for the clarification!
